default: &default
  adapter: postgresql
  encoding: unicode
  user: jpmoreira
  password: jp02120
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: library_development

